spring.application.name=employee-service
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.profiles.active=dev
